### ISSUE TITLE
Update Documentation to reflect new FFmpeg 4.0 Binaries Loading

### ISSUE THREAD

**Issue by Amyyum** [unosquare/ffmediaelement#219]
Hi, Mario I'm trying to do like the following
### Windows: Compiling, Running and Testing
```
Please note that I am unable to distribute FFmpeg's binaries because I don't know if I am allowed to do so. Follow the instructions below to compile, run and test FFME.

Clone this repository.
Download the FFmpeg win32-shared binaries from Zeranoe FFmpeg Builds.
Extract the contents of the zip file you just downloaded and go to the bin folder that got extracted. You should see 3 exe files and 8 dll files. Select and copy all of them.
Now paste all 11 files from the prior step onto a well-known folder. Take note of the full path. (I used c:\ffmpeg)
Open the solution and set the Unosquare.FFME.Windows.Sample project as the startup project. You can do this by right clicking on the project and selecting Set as startup project
Under the Unosquare.FFME.Windows.Sample project, locate the line public string FFmpegPath { get; set; } = @"C:\ffmpeg"; and replace the path so that it points to the folder where you extracted your FFmpeg binaries (dll files).
Click on Start to run the project.
You should see a sample media player. Click on the Open icon located at the bottom right and enter a URL or path to a media file.
The file or URL should play immediately, and all the properties should display to the right of the media display by clicking on the Info icon.
You can use the resulting compiled assemblies in your project without further dependencies. Look for both ffme.common.dll and ffme.win.dll.
```
I can't find 
```
public string FFmpegPath { get; set; } = @"C:\ffmpeg"; 
```
So I changed the code like this.(Of course the file of "E:\vsProjects\ffmpeg-4.0-win32-shared\bin" have the 3 exe files and 8 dll files  of ffmpeg. ) But when I started and  entered any URL or path to media file ,it will never play.I rellay don't know why.Can you help me ? Thanks very much! 

```
 // Change the default location of the ffmpeg binaries
            // You can get the binaries here: https://ffmpeg.zeranoe.com/builds/win32/shared/ffmpeg-4.0-win32-shared.zip
            MediaElement.FFmpegDirectory = @"E:\vsProjects\ffmpeg-4.0-win32-shared\bin";
```

**Comment by saturne1606** [comment]
It does not work yet with FFmpeg 4.0, get 3.4.2 version instead.

**Comment by Amyyum** [comment]
@saturne1606 Thanks for you reply. I had changed ffmpeg-4.0-win32-shared to ffmpeg-3.4.2-win32-shared, but the FFmpeg binaries  will can't be load.
```
 // Load FFmpeg binaries by Library ID
                    foreach (var lib in FFLibrary.All)
                    {
                        if ((lib.FlagId & libIdentifiers) != 0 && lib.Load(ffmpegPath))
                            registrationIds |= lib.FlagId;
                    }

```

**Comment by mariodivece** [comment]
I have updated the readme.md file to reflect changes in loading FFmpeg binaries and getting the reference player working. Reopen if the instructions are still misleading.

**Comment by Rbn3D** [comment]
I'm still unable to load FFMpeg.

The path is set correctly, just before setting the MediaElement Source, but, after debugging, seems like it's not able to load any of the libraries (Even seeing the correct path in the debugger!).

I get this error: 

> "Unable to load FFmpeg binaries from folder 'Path ommited'

(I ommited the path intentionally)

This is how my ffmpeg folder looks like (FFmpeg 4.0 win32):
![imagen](https://user-images.githubusercontent.com/4525805/41972295-bf3fe398-7a11-11e8-885a-098b46ad7f51.png)

Any help on this would be greatly appreciated
