### ISSUE TITLE
MediaElement.Dispose() hangs on awaiting Commands.Close()

### ISSUE THREAD

**Issue by xupefei** [unosquare/ffmediaelement#45]
When disposing a MediaElement instance, the application stucks at this line: https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME/MediaElement.cs#L274 and never continues.

How to reproduce:
(1) Call `Media.Dispose();` from any method, regardless whether there is a media file opened.
-or-
(2) :
```
using Unosquare.FFME;

private void AMethod()
{
    using (var element = new MediaElement())
    {
        // left empty
    }
}
```

**Comment by mariodivece** [comment]
Correct. And this is also related to #44 
The current problem is that a deadlock is created on the main thread. I know how to fix this. Just be a little patient. I am getting there :)

**Comment by mariodivece** [comment]
@xupefei could you give it another try please? It should be fixed with the new commanding changes.

**Comment by xupefei** [comment]
Hi,

I have tried the latest code, but unfortunately it still hangs at https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME/MediaElement.cs#L308.

**Comment by xupefei** [comment]
Finally I figured out why such `Commands.Close().GetAwaiter().GetResult()` will deadlock:

1. In `MediaElement.Dispose()` method we are waiting for `Commands.Close()` to finish by blocking the UI thread.
2. In  `Commands.Close()` method, there is a `renderer.Close()` for closing all existing renders.
3. In for example `AudioRenderer.Close() -> Destroy()` method, `Utils.UIInvoke()` tries to do something on UI thread and wait for finish.

Here is the deadlock. When `UIInvoke` is waiting in the 3rd step, the UI thread is already blocked by the 1st step. So the `UIInvoke` is never executed and thus `Commands.Close()` never returns.

**Comment by xupefei** [comment]
Therefore a simple solution would be rewrite the Dispose() method as follows such that it does not block UI thread:
```
private void Dispose(bool alsoManaged)
{
    if (alsoManaged)
    {
        // close current media which not blocking UI thread
        Dispatcher.InvokeAsync(() => Commands.Close(), DispatcherPriority.Send).Task.ContinueWith(t =>
        {
            if (Container != null)
            {
                Container.Dispose();
                Container = null;
            }

            if (UIPropertyUpdateTimer != null)
            {
                UIPropertyUpdateTimer.Stop();
                UIPropertyUpdateTimer.IsEnabled = false;
                UIPropertyUpdateTimer = null;
            }

            PacketReadingCycle.Dispose();
            FrameDecodingCycle.Dispose();
            BlockRenderingCycle.Dispose();
            SeekingDone.Dispose();
        });
    }
}
```

**Comment by mariodivece** [comment]
I have introduced a PumpInvokeAsync method that prevents deadlocks from the same dispatcher and continues the "pumping" of delegates on the same dispatcher. Check it out. Close this issue if it is fixed. Thanks!

**Comment by xupefei** [comment]
Amazing, everything works perfect now.
Thank you very much for the effort!

**Comment by xupefei** [comment]
Another related issue: the `ManualResetEvent`s in `MediaElement.Worker.cs` may get disposed too early:
when `IsTaskCancellationPending` in becomes true, the `while` loop is done (Line 149) and since the `PacketReadingCycle` is set, the waiter in `m.PacketReadingCycle.WaitOne();` in `CloseCommand.cs` will continue.
However, later in Line 157 the `PacketReadingCycle` is set for the 2nd time, while at this point it may be disposed by `MediaElement.Dispose()` already.
To reproduce this issue, add a short delay before Line 157:
```
if (IsTaskCancellationPending)
    Thread.Sleep(200);
// Always exit notifying the reading cycle is done.
PacketReadingCycle.Set();
```

**Comment by mariodivece** [comment]
Really good catch. I just added the check for the handle being closed. Looks like Thread.Join and async don't get along too well...

**Comment by xupefei** [comment]
Thank you very much. This issue is now fully fixed :D
